name: sphere  
version: '0.1.2'
summary: The motechat sphere system
description: |
  The base compoment for motechat.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  motebus:
    command: motebus
    plugs: [ network-bind ]
    daemon: simple
  dc:
    command: bin/dc
    plugs: [ network-bind ]
    daemon: simple

parts:
  motebus:
    plugin: gulp
    source: .
    node-engine: 10.15.3
    gulp-tasks:
      - default

  dc:
    plugin: nodejs
    source: dc
    node-engine: 10.15.3
